default: &default
  invitation_watcher:
    class: InvitationWatcherJob
    queue: default
    schedule: every day at 8:00
  school_stats_notifier:
    class: SchoolStatsNotifierJob
    queue: default
    schedule: every day at 16:15
  unlinked_metalife_users_notifier:
    class: UnlinkedMetalifeUsersNotifierJob
    queue: default
    schedule: every day at 0:05

production:
  <<: *default

development:
  <<: *default
